#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export PARTITION="${PARTITION:-A}"
export SOURCE_FEATURE_RESHAPER="${SOURCE_FEATURE_RESHAPER:-residual_temporal_conv}"
export SOURCE_FEATURE_RESHAPER_STRENGTH="${SOURCE_FEATURE_RESHAPER_STRENGTH:-0.10}"
export SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="${SOURCE_FEATURE_RESHAPER_KERNEL_SIZE:-3}"
export SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="${SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF:-0.05}"
export SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="${SOURCE_FEATURE_DUAL_CLS_TRADE_OFF:-1.00}"
export SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="${SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF:-0.05}"
export SOURCE_DOMAIN_ADAPTIVE_PHASE_WEIGHTS="${SOURCE_DOMAIN_ADAPTIVE_PHASE_WEIGHTS:-False}"
export SOURCE_DOMAIN_PHASE_BLEND_ALPHA="${SOURCE_DOMAIN_PHASE_BLEND_ALPHA:-0.00}"
export SOURCE_PHASE_MARGIN_TRADE_OFF="${SOURCE_PHASE_MARGIN_TRADE_OFF:-0.00}"
export RESHAPER_TAG="${RESHAPER_TAG:-${SOURCE_FEATURE_RESHAPER}_s${SOURCE_FEATURE_RESHAPER_STRENGTH}_k${SOURCE_FEATURE_RESHAPER_KERNEL_SIZE}_r${SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF}_dual_c${SOURCE_FEATURE_DUAL_CLS_TRADE_OFF}_rel${SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF}}"

if [ "$PARTITION" = "A" ]; then
  TASKS=(
    "france/30TXT/2017 france/31TCJ/2017"
    "france/30TXT/2017 denmark/32VNH/2017"
    "france/30TXT/2017 austria/33UVP/2017"
    "france/31TCJ/2017 france/30TXT/2017"
    "france/31TCJ/2017 denmark/32VNH/2017"
    "france/31TCJ/2017 austria/33UVP/2017"
  )
else
  TASKS=(
    "denmark/32VNH/2017 france/30TXT/2017"
    "denmark/32VNH/2017 france/31TCJ/2017"
    "denmark/32VNH/2017 austria/33UVP/2017"
    "austria/33UVP/2017 france/30TXT/2017"
    "austria/33UVP/2017 france/31TCJ/2017"
    "austria/33UVP/2017 denmark/32VNH/2017"
  )
fi

for task in "${TASKS[@]}"; do
  read -r SOURCE TARGET <<< "$task"
  SOURCE="$SOURCE" TARGET="$TARGET" bash "$SCRIPT_DIR/run_timematch_closed_set_sourcephasecompact_reshaper_dualpath.sh"
done
