#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$ROOT_DIR/logs"
RUN_TAG="${RUN_TAG:-v250_reshaper_da_ablation}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
RUN_DIR="$LOG_DIR/${RUN_TAG}_${TIMESTAMP}"
mkdir -p "$RUN_DIR"

export DATA_ROOT="${DATA_ROOT:-/data/user/DBL/timematch_data}"
export NUM_WORKERS="${NUM_WORKERS:-8}"
export TIMEMATCH_EPOCHS="${TIMEMATCH_EPOCHS:-20}"
export SOURCE_SKIP_TRAIN="True"
export SOURCE_PRETRAIN_EPOCHS="${SOURCE_PRETRAIN_EPOCHS:-100}"
export SOURCE_FEATURE_RESHAPER="${SOURCE_FEATURE_RESHAPER:-residual_temporal_conv}"
export SOURCE_FEATURE_RESHAPER_STRENGTH="${SOURCE_FEATURE_RESHAPER_STRENGTH:-0.10}"
export SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="${SOURCE_FEATURE_RESHAPER_KERNEL_SIZE:-3}"
export SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="${SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF:-0.05}"
export SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="${SOURCE_FEATURE_DUAL_CLS_TRADE_OFF:-1.00}"
export SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="${SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF:-0.03}"
export SOURCE_PHASE_PARTITION_MODE="${SOURCE_PHASE_PARTITION_MODE:-doy_gap}"
export SOURCE_SEGMENT_PARTITION_MODE="${SOURCE_SEGMENT_PARTITION_MODE:-doy_gap}"
export SOURCE_PHASE_COUNT="${SOURCE_PHASE_COUNT:-5}"
export SOURCE_SEGMENT_COUNT="${SOURCE_SEGMENT_COUNT:-5}"
export SOURCE_PHASE_GAP_THRESHOLD="${SOURCE_PHASE_GAP_THRESHOLD:-45}"
export SOURCE_PHASE_MIN_POINTS="${SOURCE_PHASE_MIN_POINTS:-3}"
export SOURCE_PHASE_MAX_POINTS="${SOURCE_PHASE_MAX_POINTS:-8}"
export SOURCE_PHASE_MAX_SPAN="${SOURCE_PHASE_MAX_SPAN:-120}"
export SOURCE_PHASE_MIN_SAMPLE_POINTS="${SOURCE_PHASE_MIN_SAMPLE_POINTS:-2}"
export SOURCE_STRUCTURE_LOSS_VERSION="${SOURCE_STRUCTURE_LOSS_VERSION:-segment_boundary_window_residual}"
export SOURCE_STRUCTURE_INTRA_TRADE_OFF="${SOURCE_STRUCTURE_INTRA_TRADE_OFF:-1.0}"
export SOURCE_STRUCTURE_TREND_TRADE_OFF="${SOURCE_STRUCTURE_TREND_TRADE_OFF:-0.05}"
export SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF="${SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF:-0.02}"
export SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF="${SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF:-0.20}"
export SOURCE_STRUCTURE_BOUNDARY_WINDOW_SIZE="${SOURCE_STRUCTURE_BOUNDARY_WINDOW_SIZE:-2}"
export SOURCE_WEIGHTS_CHECKPOINTS="${SOURCE_WEIGHTS_CHECKPOINTS:-checkpoints/epoch_50.pt}"

BLOCK_SCRIPT="$ROOT_DIR/launchers/ideas/run_timematch_closed_set_sourcephasecompact_reshaper_dualpath_source_block.sh"

echo "Launching reshaper DA ablation into $RUN_DIR"
echo "Using source checkpoint(s): $SOURCE_WEIGHTS_CHECKPOINTS"

CUDA_VISIBLE_DEVICES=0 \
  RESHAPER_TAG="v250_reshaperda_train" \
  SOURCE_FEATURE_RESHAPER_DA_MODE="train" \
  SOURCE_MODEL="pseltae_31TCJ_closedset_noshift_sourcephasecompact_p5_v250_boundarywindow_s010_rel003_ckptbank" \
  SOURCE="france/31TCJ/2017" \
  TARGETS_BLOCK=$'denmark/32VNH/2017' \
  bash "$BLOCK_SCRIPT" > "$RUN_DIR/gpu0_31TCJ_to_32VNH_train.log" 2>&1 &

CUDA_VISIBLE_DEVICES=1 \
  RESHAPER_TAG="v250_reshaperda_off" \
  SOURCE_FEATURE_RESHAPER_DA_MODE="off" \
  SOURCE_MODEL="pseltae_31TCJ_closedset_noshift_sourcephasecompact_p5_v250_boundarywindow_s010_rel003_ckptbank" \
  SOURCE="france/31TCJ/2017" \
  TARGETS_BLOCK=$'denmark/32VNH/2017' \
  bash "$BLOCK_SCRIPT" > "$RUN_DIR/gpu1_31TCJ_to_32VNH_off.log" 2>&1 &

CUDA_VISIBLE_DEVICES=2 \
  RESHAPER_TAG="v250_reshaperda_train" \
  SOURCE_FEATURE_RESHAPER_DA_MODE="train" \
  SOURCE_MODEL="pseltae_32VNH_closedset_noshift_sourcephasecompact_p5_v250_boundarywindow_s010_rel003_ckptbank" \
  SOURCE="denmark/32VNH/2017" \
  TARGETS_BLOCK=$'france/31TCJ/2017' \
  bash "$BLOCK_SCRIPT" > "$RUN_DIR/gpu2_32VNH_to_31TCJ_train.log" 2>&1 &

CUDA_VISIBLE_DEVICES=3 \
  RESHAPER_TAG="v250_reshaperda_off" \
  SOURCE_FEATURE_RESHAPER_DA_MODE="off" \
  SOURCE_MODEL="pseltae_32VNH_closedset_noshift_sourcephasecompact_p5_v250_boundarywindow_s010_rel003_ckptbank" \
  SOURCE="denmark/32VNH/2017" \
  TARGETS_BLOCK=$'france/31TCJ/2017' \
  bash "$BLOCK_SCRIPT" > "$RUN_DIR/gpu3_32VNH_to_31TCJ_off.log" 2>&1 &

wait

echo "Reshaper DA ablation finished. Logs: $RUN_DIR"
