#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

export RUN_TAG="${RUN_TAG:-v252c_structure_gate_pc}"
export ANALYSIS_SUBDIR="${ANALYSIS_SUBDIR:-${RUN_TAG}_analysis}"
export RUN_SUFFIX="${RUN_SUFFIX:-runA}"
export RESHAPER_TAG="${RESHAPER_TAG:-v252c_s010_rel003_${RUN_SUFFIX}}"
export SKIP_STRUCTURE_ANALYSIS="${SKIP_STRUCTURE_ANALYSIS:-1}"

export SOURCE_FEATURE_RESHAPER="${SOURCE_FEATURE_RESHAPER:-residual_temporal_conv}"
export SOURCE_FEATURE_RESHAPER_STRENGTH="${SOURCE_FEATURE_RESHAPER_STRENGTH:-0.10}"
export SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="${SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF:-0.03}"
export SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="${SOURCE_FEATURE_DUAL_CLS_TRADE_OFF:-1.00}"
export SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="${SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF:-0.05}"
export SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="${SOURCE_FEATURE_RESHAPER_KERNEL_SIZE:-3}"

export SOURCE_PHASE_PARTITION_MODE="${SOURCE_PHASE_PARTITION_MODE:-doy_gap}"
export SOURCE_PHASE_COUNT="${SOURCE_PHASE_COUNT:-5}"
export SOURCE_SEGMENT_PARTITION_MODE="${SOURCE_SEGMENT_PARTITION_MODE:-$SOURCE_PHASE_PARTITION_MODE}"
export SOURCE_SEGMENT_COUNT="${SOURCE_SEGMENT_COUNT:-$SOURCE_PHASE_COUNT}"
export SOURCE_PHASE_GAP_THRESHOLD="${SOURCE_PHASE_GAP_THRESHOLD:-45}"
export SOURCE_PHASE_MIN_POINTS="${SOURCE_PHASE_MIN_POINTS:-3}"
export SOURCE_PHASE_MAX_POINTS="${SOURCE_PHASE_MAX_POINTS:-8}"
export SOURCE_PHASE_MAX_SPAN="${SOURCE_PHASE_MAX_SPAN:-120}"
export SOURCE_PHASE_MIN_SAMPLE_POINTS="${SOURCE_PHASE_MIN_SAMPLE_POINTS:-2}"

export SOURCE_STRUCTURE_LOSS_VERSION="${SOURCE_STRUCTURE_LOSS_VERSION:-segment_boundary_window_residual}"
export SOURCE_STRUCTURE_INTRA_TRADE_OFF="${SOURCE_STRUCTURE_INTRA_TRADE_OFF:-1.0}"
export SOURCE_STRUCTURE_AMPLITUDE_TRADE_OFF="${SOURCE_STRUCTURE_AMPLITUDE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_INTERPHASE_TRADE_OFF="${SOURCE_STRUCTURE_INTERPHASE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_SHAPE_TRADE_OFF="${SOURCE_STRUCTURE_SHAPE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_TREND_TRADE_OFF="${SOURCE_STRUCTURE_TREND_TRADE_OFF:-0.05}"
export SOURCE_STRUCTURE_SEASON_TRADE_OFF="${SOURCE_STRUCTURE_SEASON_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF="${SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF:-0.02}"
export SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF="${SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF:-0.20}"
export SOURCE_STRUCTURE_BOUNDARY_WINDOW_SIZE="${SOURCE_STRUCTURE_BOUNDARY_WINDOW_SIZE:-2}"

# v2.5.2c: structure-based gate + per-component controller
export SOURCE_COMPONENT_GATE_ENABLE="${SOURCE_COMPONENT_GATE_ENABLE:-True}"
export SOURCE_COMPONENT_GATE_MODE="${SOURCE_COMPONENT_GATE_MODE:-structure}"
export SOURCE_COMPONENT_GATE_PROFILE_EPOCHS="${SOURCE_COMPONENT_GATE_PROFILE_EPOCHS:-10}"
export SOURCE_COMPONENT_GATE_INIT_MIN_FACTOR="${SOURCE_COMPONENT_GATE_INIT_MIN_FACTOR:-0.60}"
export SOURCE_COMPONENT_GATE_INIT_MAX_FACTOR="${SOURCE_COMPONENT_GATE_INIT_MAX_FACTOR:-1.40}"

export SOURCE_COMPONENT_CONTROLLER_ENABLE="${SOURCE_COMPONENT_CONTROLLER_ENABLE:-True}"
export SOURCE_CONTROLLER_DECAY_MODE="${SOURCE_CONTROLLER_DECAY_MODE:-per_component}"
export SOURCE_COMPONENT_CONTROLLER_WARMUP_EPOCHS="${SOURCE_COMPONENT_CONTROLLER_WARMUP_EPOCHS:-40}"
export SOURCE_COMPONENT_CONTROLLER_PATIENCE="${SOURCE_COMPONENT_CONTROLLER_PATIENCE:-4}"
export SOURCE_COMPONENT_CONTROLLER_TOLERANCE="${SOURCE_COMPONENT_CONTROLLER_TOLERANCE:-0.001}"
# Per-component decay rates (segment_inter decays fastest, dual_relation slowest)
export SOURCE_CONTROLLER_DECAY_SEGMENT_INTER="${SOURCE_CONTROLLER_DECAY_SEGMENT_INTER:-0.70}"
export SOURCE_CONTROLLER_DECAY_BOUNDARY_WINDOW="${SOURCE_CONTROLLER_DECAY_BOUNDARY_WINDOW:-0.85}"
export SOURCE_CONTROLLER_DECAY_RESHAPER="${SOURCE_CONTROLLER_DECAY_RESHAPER:-0.75}"
export SOURCE_CONTROLLER_DECAY_DUAL_RELATION="${SOURCE_CONTROLLER_DECAY_DUAL_RELATION:-0.90}"
# Per-component min factors
export SOURCE_CONTROLLER_MIN_FACTOR_SEGMENT_INTER="${SOURCE_CONTROLLER_MIN_FACTOR_SEGMENT_INTER:-0.10}"
export SOURCE_CONTROLLER_MIN_FACTOR_BOUNDARY_WINDOW="${SOURCE_CONTROLLER_MIN_FACTOR_BOUNDARY_WINDOW:-0.30}"
export SOURCE_CONTROLLER_MIN_FACTOR_RESHAPER="${SOURCE_CONTROLLER_MIN_FACTOR_RESHAPER:-0.15}"
export SOURCE_CONTROLLER_MIN_FACTOR_DUAL_RELATION="${SOURCE_CONTROLLER_MIN_FACTOR_DUAL_RELATION:-0.25}"

export SOURCE_PRETRAIN_EPOCHS="${SOURCE_PRETRAIN_EPOCHS:-50}"
export TIMEMATCH_EPOCHS="${TIMEMATCH_EPOCHS:-20}"
export NUM_WORKERS="${NUM_WORKERS:-8}"
export BATCH_SIZE="${BATCH_SIZE:-128}"

bash "$ROOT_DIR/launchers/launch_four_gpu_v223_rerun_and_structure_analysis.sh"
