#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
IDEA_DIR="$SCRIPT_DIR/ideas"
RUN_TAG="${RUN_TAG:-v251_selection_12tasks}"
LOG_DIR="${LOG_DIR:-$ROOT_DIR/logs/${RUN_TAG}_rerun_and_structure_$(date +%Y%m%d_%H%M%S)}"

mkdir -p "$LOG_DIR"

export DATA_ROOT="${DATA_ROOT:-/data/user/DBL/timematch_data}"
export OUTPUTS_ROOT="${OUTPUTS_ROOT:-outputs}"
export DEVICE="${DEVICE:-cuda}"

export RESHAPER_TAG="${RESHAPER_TAG:-v251_selection_s010_rel003}"
export SOURCE_MODEL_TAG="${SOURCE_MODEL_TAG:-$RESHAPER_TAG}"
export TARGET_MODEL_TAG="${TARGET_MODEL_TAG:-$RESHAPER_TAG}"

export SOURCE_FEATURE_RESHAPER="${SOURCE_FEATURE_RESHAPER:-residual_temporal_conv}"
export SOURCE_FEATURE_RESHAPER_STRENGTH="${SOURCE_FEATURE_RESHAPER_STRENGTH:-0.10}"
export SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="${SOURCE_FEATURE_RESHAPER_KERNEL_SIZE:-3}"
export SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="${SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF:-0.05}"
export SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="${SOURCE_FEATURE_DUAL_CLS_TRADE_OFF:-1.00}"
export SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="${SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF:-0.03}"

export SOURCE_PHASE_PARTITION_MODE="${SOURCE_PHASE_PARTITION_MODE:-doy_gap}"
export SOURCE_PHASE_COUNT="${SOURCE_PHASE_COUNT:-5}"
export SOURCE_SEGMENT_PARTITION_MODE="${SOURCE_SEGMENT_PARTITION_MODE:-$SOURCE_PHASE_PARTITION_MODE}"
export SOURCE_SEGMENT_COUNT="${SOURCE_SEGMENT_COUNT:-$SOURCE_PHASE_COUNT}"
export SOURCE_PHASE_GAP_THRESHOLD="${SOURCE_PHASE_GAP_THRESHOLD:-45}"
export SOURCE_PHASE_MIN_POINTS="${SOURCE_PHASE_MIN_POINTS:-3}"
export SOURCE_PHASE_MAX_POINTS="${SOURCE_PHASE_MAX_POINTS:-8}"
export SOURCE_PHASE_MAX_SPAN="${SOURCE_PHASE_MAX_SPAN:-120}"
export SOURCE_PHASE_MIN_SAMPLE_POINTS="${SOURCE_PHASE_MIN_SAMPLE_POINTS:-2}"

export SOURCE_STRUCTURE_LOSS_VERSION="${SOURCE_STRUCTURE_LOSS_VERSION:-segment_boundary_window_residual}"
export SOURCE_STRUCTURE_INTRA_TRADE_OFF="${SOURCE_STRUCTURE_INTRA_TRADE_OFF:-1.0}"
export SOURCE_STRUCTURE_AMPLITUDE_TRADE_OFF="${SOURCE_STRUCTURE_AMPLITUDE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_INTERPHASE_TRADE_OFF="${SOURCE_STRUCTURE_INTERPHASE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_SHAPE_TRADE_OFF="${SOURCE_STRUCTURE_SHAPE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_TREND_TRADE_OFF="${SOURCE_STRUCTURE_TREND_TRADE_OFF:-0.05}"
export SOURCE_STRUCTURE_SEASON_TRADE_OFF="${SOURCE_STRUCTURE_SEASON_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF="${SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF:-0.02}"
export SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF="${SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF:-0.20}"
export SOURCE_STRUCTURE_BOUNDARY_WINDOW_SIZE="${SOURCE_STRUCTURE_BOUNDARY_WINDOW_SIZE:-2}"

export SOURCE_PRETRAIN_EPOCHS="${SOURCE_PRETRAIN_EPOCHS:-100}"
export TIMEMATCH_EPOCHS="${TIMEMATCH_EPOCHS:-20}"
export NUM_WORKERS="${NUM_WORKERS:-8}"
export SOURCE_CHECKPOINT_EPOCHS="${SOURCE_CHECKPOINT_EPOCHS:-30,50,70,100}"
export SOURCE_CHECKPOINT_DIRNAME="${SOURCE_CHECKPOINT_DIRNAME:-checkpoints}"
export SOURCE_WEIGHTS_CHECKPOINTS="${SOURCE_WEIGHTS_CHECKPOINTS:-checkpoints/epoch_30.pt,checkpoints/epoch_50.pt,checkpoints/epoch_70.pt,checkpoints/epoch_100.pt}"
export SOURCE_SKIP_TRAIN="${SOURCE_SKIP_TRAIN:-0}"

export SELECTION_WARMUP_EPOCHS="${SELECTION_WARMUP_EPOCHS:-5}"
export SELECTION_COVERAGE_WEIGHT="${SELECTION_COVERAGE_WEIGHT:-1.0}"
export SELECTION_ENTROPY_WEIGHT="${SELECTION_ENTROPY_WEIGHT:-0.5}"
export SELECTION_AGREEMENT_WEIGHT="${SELECTION_AGREEMENT_WEIGHT:-0.5}"
export SELECTION_CONFIDENCE_WEIGHT="${SELECTION_CONFIDENCE_WEIGHT:-0.5}"

run_source_block() {
  local gpu_id="$1"
  local source_dataset="$2"
  local targets_block="$3"
  local source_tile
  source_tile="$(echo "$source_dataset" | cut -d'/' -f2)"
  local log_file="$LOG_DIR/gpu${gpu_id}_${source_tile}_${RUN_TAG}_tasks.log"

  (
    CUDA_VISIBLE_DEVICES="$gpu_id" \
      SOURCE="$source_dataset" \
      TARGETS_BLOCK="$targets_block" \
      bash "$IDEA_DIR/run_timematch_closed_set_sourcephasecompact_v251_selection_block.sh"
  ) > "$log_file" 2>&1 &
}

run_source_block 0 "france/30TXT/2017" $'france/31TCJ/2017\ndenmark/32VNH/2017\naustria/33UVP/2017'
run_source_block 1 "france/31TCJ/2017" $'france/30TXT/2017\ndenmark/32VNH/2017\naustria/33UVP/2017'
run_source_block 2 "denmark/32VNH/2017" $'france/30TXT/2017\nfrance/31TCJ/2017\naustria/33UVP/2017'
run_source_block 3 "austria/33UVP/2017" $'france/30TXT/2017\nfrance/31TCJ/2017\ndenmark/32VNH/2017'

wait

echo "Logs saved to: $LOG_DIR"
echo "Training logs:"
echo "  $LOG_DIR/gpu0_30TXT_${RUN_TAG}_tasks.log"
echo "  $LOG_DIR/gpu1_31TCJ_${RUN_TAG}_tasks.log"
echo "  $LOG_DIR/gpu2_32VNH_${RUN_TAG}_tasks.log"
echo "  $LOG_DIR/gpu3_33UVP_${RUN_TAG}_tasks.log"
