#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IDEA_DIR="$SCRIPT_DIR/ideas"
ANALYSIS_DIR="$SCRIPT_DIR/analysis"
LOG_DIR="${LOG_DIR:-$SCRIPT_DIR/../logs/v232_plus_analysis_$(date +%Y%m%d_%H%M%S)}"
mkdir -p "$LOG_DIR"

RESHAPER_KIND="${SOURCE_FEATURE_RESHAPER:-residual_temporal_conv}"
RESHAPER_STRENGTH="${SOURCE_FEATURE_RESHAPER_STRENGTH:-0.10}"
RESHAPER_KERNEL_SIZE="${SOURCE_FEATURE_RESHAPER_KERNEL_SIZE:-3}"
RESHAPER_REG_TRADE_OFF="${SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF:-0.05}"
DUAL_CLS_TRADE_OFF="${SOURCE_FEATURE_DUAL_CLS_TRADE_OFF:-1.00}"
DUAL_REL_TRADE_OFF="${SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF:-0.03}"
SOURCE_PHASE_MARGIN_TRADE_OFF="${SOURCE_PHASE_MARGIN_TRADE_OFF:-0.01}"
RESHAPER_TAG="${RESHAPER_TAG:-v232_residual_s010_rel003_margin001}"

TASKS_GPU0=$'france/30TXT/2017 france/31TCJ/2017\nfrance/30TXT/2017 denmark/32VNH/2017\nfrance/31TCJ/2017 france/30TXT/2017\nfrance/31TCJ/2017 denmark/32VNH/2017'
TASKS_GPU1=$'france/30TXT/2017 austria/33UVP/2017\nfrance/31TCJ/2017 austria/33UVP/2017\ndenmark/32VNH/2017 france/30TXT/2017\ndenmark/32VNH/2017 france/31TCJ/2017'
TASKS_GPU2=$'denmark/32VNH/2017 austria/33UVP/2017\naustria/33UVP/2017 france/30TXT/2017\naustria/33UVP/2017 france/31TCJ/2017\naustria/33UVP/2017 denmark/32VNH/2017'

echo "[INFO] Logs: $LOG_DIR"

CUDA_VISIBLE_DEVICES=0 \
TASKS_BLOCK="$TASKS_GPU0" \
SOURCE_FEATURE_RESHAPER="$RESHAPER_KIND" \
SOURCE_FEATURE_RESHAPER_STRENGTH="$RESHAPER_STRENGTH" \
SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="$RESHAPER_KERNEL_SIZE" \
SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="$RESHAPER_REG_TRADE_OFF" \
SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="$DUAL_CLS_TRADE_OFF" \
SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="$DUAL_REL_TRADE_OFF" \
SOURCE_PHASE_MARGIN_TRADE_OFF="$SOURCE_PHASE_MARGIN_TRADE_OFF" \
RESHAPER_TAG="$RESHAPER_TAG" \
bash "$IDEA_DIR/run_timematch_closed_set_sourcephasecompact_reshaper_dualpath_tasklist.sh" \
> "$LOG_DIR/gpu0_v232_tasks.log" 2>&1 &

CUDA_VISIBLE_DEVICES=1 \
TASKS_BLOCK="$TASKS_GPU1" \
SOURCE_FEATURE_RESHAPER="$RESHAPER_KIND" \
SOURCE_FEATURE_RESHAPER_STRENGTH="$RESHAPER_STRENGTH" \
SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="$RESHAPER_KERNEL_SIZE" \
SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="$RESHAPER_REG_TRADE_OFF" \
SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="$DUAL_CLS_TRADE_OFF" \
SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="$DUAL_REL_TRADE_OFF" \
SOURCE_PHASE_MARGIN_TRADE_OFF="$SOURCE_PHASE_MARGIN_TRADE_OFF" \
RESHAPER_TAG="$RESHAPER_TAG" \
bash "$IDEA_DIR/run_timematch_closed_set_sourcephasecompact_reshaper_dualpath_tasklist.sh" \
> "$LOG_DIR/gpu1_v232_tasks.log" 2>&1 &

CUDA_VISIBLE_DEVICES=2 \
TASKS_BLOCK="$TASKS_GPU2" \
SOURCE_FEATURE_RESHAPER="$RESHAPER_KIND" \
SOURCE_FEATURE_RESHAPER_STRENGTH="$RESHAPER_STRENGTH" \
SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="$RESHAPER_KERNEL_SIZE" \
SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="$RESHAPER_REG_TRADE_OFF" \
SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="$DUAL_CLS_TRADE_OFF" \
SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="$DUAL_REL_TRADE_OFF" \
SOURCE_PHASE_MARGIN_TRADE_OFF="$SOURCE_PHASE_MARGIN_TRADE_OFF" \
RESHAPER_TAG="$RESHAPER_TAG" \
bash "$IDEA_DIR/run_timematch_closed_set_sourcephasecompact_reshaper_dualpath_tasklist.sh" \
> "$LOG_DIR/gpu2_v232_tasks.log" 2>&1 &

CUDA_VISIBLE_DEVICES=3 \
DEVICE=cuda \
bash "$ANALYSIS_DIR/run_encoded_feature_dimension_analysis_v222.sh" \
> "$LOG_DIR/gpu3_dimension_analysis.log" 2>&1 &

wait
