#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BLOCK_SCRIPT="$ROOT_DIR/launchers/ideas/run_timematch_closed_set_sourcephasecompact_v255_allcheckpoints_block.sh"

BATCH_STAMP="${BATCH_STAMP:-$(date +%Y%m%d_%H%M%S)}"
RUN_TAG="${RUN_TAG:-v244b_prototype_dynamics_12tasks_${BATCH_STAMP}}"
LOG_DIR="${LOG_DIR:-$ROOT_DIR/logs/${RUN_TAG}}"
GPU_IDS="${GPU_IDS:-0,1,2,3}"

mkdir -p "$LOG_DIR"

export DATA_ROOT="${DATA_ROOT:-/data/user/DBL/timematch_data}"
export SOURCE_PRETRAIN_EPOCHS="${SOURCE_PRETRAIN_EPOCHS:-50}"
export TIMEMATCH_EPOCHS="${TIMEMATCH_EPOCHS:-20}"
export NUM_WORKERS="${NUM_WORKERS:-8}"
export BATCH_SIZE="${BATCH_SIZE:-128}"
export SOURCE_CHECKPOINT_EPOCHS="${SOURCE_CHECKPOINT_EPOCHS:-50}"
export SOURCE_WEIGHTS_CHECKPOINTS="${SOURCE_WEIGHTS_CHECKPOINTS:-model.pt}"

# v2.4.4b: non-segmented global trajectory compactness + weak prototype dynamics.
export SOURCE_FEATURE_RESHAPER="${SOURCE_FEATURE_RESHAPER:-residual_temporal_conv}"
export SOURCE_FEATURE_RESHAPER_STRENGTH="${SOURCE_FEATURE_RESHAPER_STRENGTH:-0.10}"
export SOURCE_FEATURE_RESHAPER_KERNEL_SIZE="${SOURCE_FEATURE_RESHAPER_KERNEL_SIZE:-3}"
export SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF="${SOURCE_FEATURE_RESHAPER_REG_TRADE_OFF:-0.05}"
export SOURCE_FEATURE_DUAL_CLS_TRADE_OFF="${SOURCE_FEATURE_DUAL_CLS_TRADE_OFF:-1.00}"
export SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF="${SOURCE_FEATURE_DUAL_RELATION_TRADE_OFF:-0.03}"

export SOURCE_PHASE_PARTITION_MODE="${SOURCE_PHASE_PARTITION_MODE:-uniform}"
export SOURCE_SEGMENT_PARTITION_MODE="${SOURCE_SEGMENT_PARTITION_MODE:-uniform}"
export SOURCE_PHASE_COUNT="${SOURCE_PHASE_COUNT:-1}"
export SOURCE_SEGMENT_COUNT="${SOURCE_SEGMENT_COUNT:-1}"
export SOURCE_PHASE_MIN_SAMPLE_POINTS="${SOURCE_PHASE_MIN_SAMPLE_POINTS:-1}"

export SOURCE_STRUCTURE_LOSS_VERSION="${SOURCE_STRUCTURE_LOSS_VERSION:-trajectory_prototype_dynamics_v244b}"
export SOURCE_STRUCTURE_INTRA_TRADE_OFF="${SOURCE_STRUCTURE_INTRA_TRADE_OFF:-5.0}"
export SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_TRADE_OFF="${SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_TRADE_OFF:-0.01}"
export SOURCE_STRUCTURE_TRAJECTORY_POOLING="${SOURCE_STRUCTURE_TRAJECTORY_POOLING:-meanmax}"
export SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_MODE="${SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_MODE:-cosine}"
export SOURCE_STRUCTURE_AMPLITUDE_TRADE_OFF="${SOURCE_STRUCTURE_AMPLITUDE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_INTERPHASE_TRADE_OFF="${SOURCE_STRUCTURE_INTERPHASE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_SHAPE_TRADE_OFF="${SOURCE_STRUCTURE_SHAPE_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_TREND_TRADE_OFF="${SOURCE_STRUCTURE_TREND_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_SEASON_TRADE_OFF="${SOURCE_STRUCTURE_SEASON_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF="${SOURCE_STRUCTURE_SEGMENT_INTER_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF="${SOURCE_STRUCTURE_BOUNDARY_WINDOW_TRADE_OFF:-0.00}"
export SOURCE_STRUCTURE_WARP_INVARIANT_TRADE_OFF="${SOURCE_STRUCTURE_WARP_INVARIANT_TRADE_OFF:-0.00}"

export SOURCE_PHASE_GRID_TRADE_OFF="${SOURCE_PHASE_GRID_TRADE_OFF:-0.0}"
export SOURCE_STRUCTURE_ADAPTIVE_WEIGHTS="${SOURCE_STRUCTURE_ADAPTIVE_WEIGHTS:-False}"
export SOURCE_STRUCTURE_ADAPTIVITY_MODE="${SOURCE_STRUCTURE_ADAPTIVITY_MODE:-none}"

IFS=',' read -r -a GPU_ITEMS <<< "$GPU_IDS"

echo "Logs saved under: $LOG_DIR"
echo "SOURCE_PRETRAIN_EPOCHS=$SOURCE_PRETRAIN_EPOCHS TIMEMATCH_EPOCHS=$TIMEMATCH_EPOCHS"
echo "SOURCE_STRUCTURE_LOSS_VERSION=$SOURCE_STRUCTURE_LOSS_VERSION"
echo "SOURCE_STRUCTURE_INTRA_TRADE_OFF=$SOURCE_STRUCTURE_INTRA_TRADE_OFF"
echo "SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_TRADE_OFF=$SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_TRADE_OFF"
echo "SOURCE_STRUCTURE_TRAJECTORY_POOLING=$SOURCE_STRUCTURE_TRAJECTORY_POOLING"
echo "SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_MODE=$SOURCE_STRUCTURE_PROTOTYPE_DYNAMICS_MODE"

run_source_block() {
  local source_name="$1"
  local source_dataset="$2"
  local targets_block="$3"
  gpu_id="${GPU_ITEMS[$((job_idx % ${#GPU_ITEMS[@]}))]}"
  job_tag="v244b_${source_name}_${BATCH_STAMP}"
  log_file="$LOG_DIR/${job_tag}.log"

  echo "START|${job_tag}|gpu=${gpu_id}|source=${source_dataset}"
  (
    CUDA_VISIBLE_DEVICES="$gpu_id" \
      SOURCE="$source_dataset" \
      TARGETS_BLOCK="$targets_block" \
      VARIANT_NAME="v244b_prototype_dynamics" \
      SOURCE_MODEL_TAG="${job_tag}_source" \
      RESHAPER_TAG="${job_tag}" \
      TARGET_MODEL_TAG="${job_tag}" \
      bash "$BLOCK_SCRIPT"
  ) > "$log_file" 2>&1 &

  job_idx=$((job_idx + 1))
}

job_idx=0
run_source_block "FR1" "france/30TXT/2017" $'france/31TCJ/2017\ndenmark/32VNH/2017\naustria/33UVP/2017'
run_source_block "FR2" "france/31TCJ/2017" $'france/30TXT/2017\ndenmark/32VNH/2017\naustria/33UVP/2017'
run_source_block "DK1" "denmark/32VNH/2017" $'france/30TXT/2017\nfrance/31TCJ/2017\naustria/33UVP/2017'
run_source_block "AT1" "austria/33UVP/2017" $'france/30TXT/2017\nfrance/31TCJ/2017\ndenmark/32VNH/2017'

wait

echo "All v2.4.4b prototype-dynamics 12-task jobs finished."
echo "Logs saved under: $LOG_DIR"
